export const releasedTopics = [
  {
    theme: "css",
    title: "Flexbox cheat sheet",
    category: "cheat sheets",
    released: true,
    path: "/topics/cheatsheets/flexbox",
  },
];

export const unreleasedTopics = [
  {
    theme: "css",
    title: "Css Properties",
    category: "cheat sheets",
    released: false,
    path: false,
  },
  {
    theme: "css",
    title: "Grid cheat sheet",
    category: "cheat sheets",
    released: false,
    path: false,
  },
  {
    theme: "js",
    title: "Types:\nbasics, pitfalls",
    category: "cheat sheets",
    released: false,
    path: false,
  },
  {
    theme: "js",
    title: "Coercion:\nin-depth mechanics",
    category: "cheat sheets",
    released: false,
    path: false,
  },
  {
    theme: "js",
    title: "Scope in javascript",
    category: "cheat sheets",
    released: false,
    path: false,
  },
  {
    theme: "js",
    title: "Closures",
    category: "cheat sheets",
    released: false,
    path: false,
  },
  {
    theme: "js",
    title: "Variable declaration:\na war on var?",
    category: "cheat sheets",
    released: false,
    path: false,
  },
  {
    theme: "js",
    title: "Functional programing:\noverview",
    category: "cheat sheets",
    released: false,
    path: false,
  },
  {
    theme: "react",
    title: "Hooks:\nIntroduction",
    category: "article",
    released: false,
    path: false,
  },
  {
    theme: "react",
    title: "Hooks:\nuseState",
    category: "article",
    released: false,
    path: false,
  },
  {
    theme: "react",
    title: "Hooks:\nuseEffect",
    category: "article",
    released: false,
    path: false,
  },
  {
    theme: "react",
    title: "Hooks:\nuseLayoutEffect",
    category: "article",
    released: false,
    path: false,
  },

  {
    theme: "html",
    title: "Tags: \ncheat sheet",
    category: "article",
    released: false,
    path: false,
  },
  {
    theme: "html",
    title: "Tags:\nmarkup validity",
    category: "article",
    released: false,
    path: false,
  },
  {
    theme: "html",
    title: "Accessibility",
    category: "article",
    released: false,
    path: false,
  },
  {
    theme: "html",
    title: "SEO",
    category: "article",
    released: false,
    path: false,
  },
];
